# Generated by Django 5.0.1 on 2024-01-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField()),
                ('title', models.CharField(max_length=30)),
                ('short_content', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('0', 'introduce'), ('1', 'strengths')], max_length=1, null=True)),
            ],
        ),
    ]
