# Generated by Django 5.0.1 on 2024-01-24 06:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images')),
                ('link', models.TextField()),
            ],
            options={
                'verbose_name': 'Quảng cáo',
                'verbose_name_plural': 'Quảng cáo',
            },
        ),
        migrations.CreateModel(
            name='Advertisement2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images', verbose_name='Ảnh đại diện')),
                ('image1', models.FileField(blank=True, null=True, unique=True, upload_to='static/images', verbose_name='Ảnh slider 1')),
                ('image2', models.FileField(blank=True, null=True, unique=True, upload_to='static/images', verbose_name='Ảnh slider 2')),
                ('image3', models.FileField(blank=True, null=True, unique=True, upload_to='static/images', verbose_name='Ảnh slider 3')),
                ('image4', models.FileField(blank=True, null=True, unique=True, upload_to='static/images', verbose_name='Ảnh slider 4')),
                ('image5', models.FileField(blank=True, null=True, unique=True, upload_to='static/images', verbose_name='Ảnh slider 5')),
                ('image6', models.FileField(blank=True, null=True, unique=True, upload_to='static/images', verbose_name='Ảnh slider 6')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('price', models.CharField(max_length=50, verbose_name='Giá tiền')),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tin rao',
                'verbose_name_plural': 'Tin rao',
            },
        ),
        migrations.CreateModel(
            name='CategoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Danh mục dự án',
                'verbose_name_plural': 'Danh mục dự án',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('note', models.TextField()),
                ('read', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Liên hệ',
                'verbose_name_plural': 'Liên hệ',
            },
        ),
        migrations.CreateModel(
            name='Introduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('short_content', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('0', 'introduce'), ('1', 'strengths')], max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Giới thiệu',
                'verbose_name_plural': 'Giới thiệu',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.FileField(unique=True, upload_to='static/images')),
            ],
            options={
                'verbose_name': 'Thành viên',
                'verbose_name_plural': 'Thành viên',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Trang',
                'verbose_name_plural': 'Trang',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images')),
                ('link', models.TextField(default='#')),
            ],
            options={
                'verbose_name': 'Đối tác',
                'verbose_name_plural': 'Đối tác',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images')),
                ('video', models.FileField(unique=True, upload_to='static/images')),
                ('title', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Sitetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images')),
                ('title', models.CharField(max_length=255)),
                ('short_content', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('category_sitetour', models.CharField(blank=True, choices=[('0', 'Nổi bật')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Kiểu dự án',
                'verbose_name_plural': 'Kiểu dự án',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='InfoAdvertisement2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('advertisement2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_results', to='ui.advertisement2')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images')),
                ('page', models.ManyToManyField(to='ui.page')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images')),
                ('title', models.CharField(max_length=255)),
                ('short_content', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('project_sell', models.CharField(blank=True, choices=[('0', 'Dự án toàn quốc'), ('1', 'Bất động sản bán lẻ'), ('2', 'Dự án nổi bật')], default='0', max_length=2, null=True)),
                ('category', models.ManyToManyField(to='ui.categoryproject')),
                ('type_project', models.ManyToManyField(to='ui.typeproject')),
            ],
            options={
                'verbose_name': 'Dự án',
                'verbose_name_plural': 'Dự án',
            },
        ),
        migrations.CreateModel(
            name='InfoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_results', to='ui.project')),
            ],
        ),
        migrations.CreateModel(
            name='InfoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_results', to='ui.review')),
            ],
        ),
        migrations.CreateModel(
            name='InfoSitetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('sitetour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitetour_results', to='ui.sitetour')),
            ],
        ),
    ]
