# Generated by Django 5.0.1 on 2024-01-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_alter_introduce_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.FileField(upload_to='static/images')),
            ],
        ),
    ]
