# Generated by Django 5.0.1 on 2024-01-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.FileField(unique=True, upload_to='ui/static/images'),
        ),
    ]
