# Generated by Django 5.0.1 on 2024-01-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images')),
                ('title', models.CharField(max_length=255)),
                ('short_content', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('info', models.ManyToManyField(to='ui.infoproject')),
                ('type_project', models.ManyToManyField(to='ui.typeproject')),
            ],
        ),
    ]
