# Generated by Django 5.0.1 on 2024-01-17 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_infoproject_typeproject_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='info',
        ),
        migrations.AddField(
            model_name='project',
            name='info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.infoproject'),
        ),
    ]
