# Generated by Django 5.0.1 on 2024-01-17 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_remove_project_info_project_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoproject',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.project'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='info',
        ),
        migrations.AddField(
            model_name='project',
            name='info',
            field=models.ManyToManyField(limit_choices_to={'project__isnull': True}, to='ui.infoproject'),
        ),
    ]
