# Generated by Django 5.0.1 on 2024-01-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_remove_project_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoproject',
            old_name='project_id',
            new_name='project',
        ),
    ]
