# Generated by Django 5.0.1 on 2024-01-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0014_rename_project_id_infoproject_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(to='ui.categoryproject'),
        ),
    ]
