# Generated by Django 5.0.1 on 2024-01-18 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_categoryproject_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_results', to='ui.project'),
        ),
    ]
