# Generated by Django 5.0.1 on 2024-01-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0019_remove_infoproject_review_inforeview'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
