# Generated by Django 5.0.1 on 2024-01-19 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0020_page_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='static/images')),
                ('title', models.CharField(max_length=255)),
                ('short_content', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('price', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoSitetour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('sitetour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sitetour_results', to='ui.sitetour')),
            ],
        ),
    ]
