# Generated by Django 5.0.1 on 2024-01-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0021_sitetour_infositetour'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_sell',
            field=models.CharField(blank=True, choices=[('0', 'Dự án toàn quốc'), ('1', 'Bất động sản bán lẻ')], default='0', max_length=2, null=True),
        ),
    ]
