# Generated by Django 5.0.1 on 2024-01-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0022_project_project_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_sell',
            field=models.CharField(blank=True, choices=[('0', 'Dự án toàn quốc'), ('1', 'Bất động sản bán lẻ'), ('2', 'Dự án nổi bật')], default='0', max_length=2, null=True),
        ),
    ]
