# Generated by Django 5.0.1 on 2024-01-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0023_alter_project_project_sell'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetour',
            name='category_sitetour',
            field=models.CharField(blank=True, choices=[('0', 'Nổi bật')], max_length=1, null=True),
        ),
    ]
