# Generated by Django 5.0.1 on 2024-01-23 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0024_sitetour_category_sitetour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(unique=True, upload_to='static/images', verbose_name='Ảnh đại diện')),
                ('image1', models.FileField(blank=True, null=True, unique=True, upload_to='static/images', verbose_name='Ảnh slider 1')),
                ('image2', models.FileField(blank=True, null=True, unique=True, upload_to='static/images', verbose_name='Ảnh slider 2')),
                ('image3', models.FileField(blank=True, null=True, unique=True, upload_to='static/images', verbose_name='Ảnh slider 3')),
                ('image4', models.FileField(blank=True, null=True, unique=True, upload_to='static/images', verbose_name='Ảnh slider 4')),
                ('image5', models.FileField(blank=True, null=True, unique=True, upload_to='static/images', verbose_name='Ảnh slider 5')),
                ('image6', models.FileField(blank=True, null=True, unique=True, upload_to='static/images', verbose_name='Ảnh slider 6')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Quảng cáo', 'verbose_name_plural': 'Quảng cáo'},
        ),
        migrations.AlterModelOptions(
            name='categoryproject',
            options={'verbose_name': 'Danh mục dự án', 'verbose_name_plural': 'Danh mục dự án'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Liên hệ', 'verbose_name_plural': 'Liên hệ'},
        ),
        migrations.AlterModelOptions(
            name='introduce',
            options={'verbose_name': 'Giới thiệu', 'verbose_name_plural': 'Giới thiệu'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Thành viên', 'verbose_name_plural': 'Thành viên'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Trang', 'verbose_name_plural': 'Trang'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Đối tác', 'verbose_name_plural': 'Đối tác'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Dự án', 'verbose_name_plural': 'Dự án'},
        ),
        migrations.AlterModelOptions(
            name='typeproject',
            options={'verbose_name': 'Kiểu dự án', 'verbose_name_plural': 'Kiểu dự án'},
        ),
        migrations.AlterField(
            model_name='sitetour',
            name='image',
            field=models.FileField(unique=True, upload_to='static/images'),
        ),
        migrations.CreateModel(
            name='InfoAdvertisement2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('advertisement2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_results', to='ui.advertisement2')),
            ],
        ),
    ]
