# Generated by Django 5.0.1 on 2024-01-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0025_advertisement2_alter_advertisement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement2',
            options={'verbose_name': 'Tin rao', 'verbose_name_plural': 'Tin rao'},
        ),
        migrations.AddField(
            model_name='advertisement2',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advertisement2',
            name='content',
            field=models.TextField(verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='advertisement2',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Giá tiền'),
        ),
        migrations.AlterField(
            model_name='advertisement2',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tiêu đề'),
        ),
    ]
