# Generated by Django 5.0.1 on 2024-01-23 02:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0026_alter_advertisement2_options_advertisement2_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement2',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
